version: "3.8"
services:
  app:
    build:
      context: ./app
      args:
        TASK_SERVICE_URL: http://localhost:8000
        PROJECT_SERVICE_URL: http://localhost:8001
        BUILD_PROFILE: dev
    ports:
      - "80:80"
  tasksvc:
    build:
      context: ./task-service
      args:
        CARGO_INSTALL_OPTIONS: "--debug"
    ports:
      - "8000:80"
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: secret
      ELASTIC_URL: http://es:9200
      PROJECT_SERVICE_URL: http://projectsvc
  projectsvc:
    build:
      context: ./project-service
      args:
        CARGO_INSTALL_OPTIONS: "--debug"
    ports:
      - "8001:80"
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: secret
      ELASTIC_URL: http://es:9200
  es:
    image: elasticsearch:7.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ELASTIC_PASSWORD: secret
  kib:
    image: kibana:7.9.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
