apiVersion: v1
kind: Service
metadata:
  name: project-svc
spec:
  selector:
    app: project
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deploy
  labels:
    app: project
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: christianfosli/taskboard-project-service
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
        - name: RUST_LOG
          value: info
        - name: ELASTIC_URL
          value: https://taskboard-es-http:9200
        - name: ELASTIC_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskboard-es-elastic-user
              key: elastic
        - name: TASK_SERVICE_URL
          value: http://task-svc

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: project-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-deploy
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
