apiVersion: v1
kind: Service
metadata:
  name: task-svc
spec:
  selector:
    app: task
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deploy
  labels:
    app: task
spec:
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-logs-container: task
    spec:
      containers:
      - name: task
        image: christianfosli/taskboard-task-service
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
        - name: RUST_LOG
          value: info
        - name: ELASTIC_URL
          value: http://taskboard-es-http:9200
        - name: ELASTIC_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskboard-es-elastic-user
              key: elastic
        - name: PROJECT_SERVICE_URL
          value: http://project-svc

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: task-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-deploy
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
