apiVersion: v1
kind: Service
metadata:
  name: task-svc
spec:
  selector:
    app: task
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deploy
  labels:
    app: task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: christianfosli/taskboard-task-service
        ports:
        - containerPort: 80
        env:
        - name: ELASTIC_URL
          value: https://taskboard-es-http:9200
        - name: ELASTIC_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: taskboard-es-elastic-user
              key: elastic
