apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.taskboard.cloud
    secretName: tls-cert
  rules:
  - host: www.taskboard.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskboard-app-svc
            port:
              number: 80
