apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: taskboard
spec:
  version: 7.12.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          linkerd.io/inject: enabled
          kubectl.kubernetes.io/default-logs-container: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          resources:
            requests:
              memory: 1Gi
              cpu: 0.25
            limits:
              memory: 1Gi
              cpu: 1
        automountServiceAccountToken: true
  updateStrategy:
    changeBudget:
      # I don't have enough memory to scale up during rolling upgrade
      maxSurge: 0
      maxUnavailable: 1
