apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-monitor-ingress
  namespace: ${namespace}
  labels:
    app: ${ingress_app_name}
    # kube-prometheus-stack helm chart configures prometheus such that
    # ServiceMonitor/PodMonitor must be tagged with their release name
    release: ${release_name}
spec:
  namespaceSelector:
    matchNames:
    - ${ingress_namespace}
  selector:
    matchLabels:
      app.kubernetes.io/name: ${ingress_app_name}
  endpoints:
  - port: metrics
