apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: taskboard
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: ${elasticsearch_name}
  config:
    server:
      basePath: /kibana
  podTemplate:
    spec:
      containers:
      - name: kibana
        readinessProbe:
          # Default is hardcoded to /login, so changing base path requires changing here too
          httpGet:
            path: /kibana/login
            port: https
