apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-ingress
  namespace: ${namespace}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ${secret}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication is required to view detailed metrics'
spec:
  ingressClassName: nginx
  tls:
  - host:
    - metrics.taskboard.cloud
    secretName: tls-cert
  rules:
  - host: metrics.taskboard.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 8084
