apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
spec:
  secretName: tls-cert
  privateKey:
    algorithm: ECDSA
  dnsNames:
  - taskboard.cloud
  - www.taskboard.cloud
  - api.taskboard.cloud
  - metrics.taskboard.cloud
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
