apiVersion: v1
kind: Service
metadata:
  name: taskboard-app-svc
spec:
  selector:
    app: taskboard-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-app-deploy
  labels:
    app: taskboard-app
spec:
  selector:
    matchLabels:
      app: taskboard-app
  template:
    metadata:
      labels:
        app: taskboard-app
    spec:
      containers:
      - name: taskboard-app
        image: christianfosli/taskboard-app
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 100m

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: taskboard-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskboard-app-deploy
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
