[package]
name = "taskboard-api"
version = "0.1.0"
authors = ["Christian Fosli <cfosli@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
pretty_env_logger = "0.3"
log = "0.4"
