name: project-service

on:
  push:
    branches: [master]
    paths:
      - project-service/**
      - .github/workflows/project-service.yml
  pull_request:
    branches: [master]
    paths:
      - project-service/**
      - .github/workflows/project-service.yml

defaults:
  run:
    working-directory: project-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        run: echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: |
          docker build \
            -t christianfosli/taskboard-project-service:"$GITHUB_SHA" \
            -t christianfosli/taskboard-project-service:latest .
        env:
          DOCKER_BUILDKIT: 1
      - name: push
        run: |
          docker push christianfosli/taskboard-project-service:"$GITHUB_SHA"
          docker push christianfosli/taskboard-project-service:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: login az
        run: |
          az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID"
          az account set -s "$SUBSCRIPTION"
        env:
          CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          SUBSCRIPTION: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: login kubectl
        run: |
          az aks get-credentials -n "aks-taskboard" -g "rg-taskboard"
          kubectl version --short
      - name: patch manifest
        run: sed -i "s|christianfosli/taskboard-project-service|christianfosli/taskboard-project-service:$GITHUB_SHA|" k8s.yml
      - run: kubectl apply -f k8s.yml
      - name: rollout status
        run: |
          kubectl rollout status deployment project-deploy || \
            (printf "\ndeploy failed!, rolling back...\n\n"; \
             kubectl rollout undo deployment project-deploy; \
             exit 1)
