name: todo-api

on:
  push:
    branches: [master]
    paths:
      - api/*
      - .github/workflows/todo-api.yml
  pull_request:
    branches: [master]
    paths:
      - api/*
      - .github/workflows/todo-api.yml

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: build
        run: docker build -t christianfosli/todo-api:latest .
      - name: push
        run: docker push christianfosli/todo-api:latest
